### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: android/os/Looper in: DefaultStore.kt:31

### ISSUE THREAD

**Issue by Shabinder** [badoo/Decompose#64]
**Caused by: java.lang.NoClassDefFoundError: android/os/Looper**
        at kotlinx.coroutines.android.AndroidDispatcherFactory.createDispatcher(HandlerDispatcher.kt:55)
        at kotlinx.coroutines.android.AndroidDispatcherFactory.createDispatcher(HandlerDispatcher.kt:52)
        at kotlinx.coroutines.internal.MainDispatchersKt.tryCreateDispatcher(MainDispatchers.kt:57)
        at kotlinx.coroutines.internal.MainDispatcherLoader.loadMainDispatcher(MainDispatchers.kt:38)
        at kotlinx.coroutines.internal.MainDispatcherLoader.<clinit>(MainDispatchers.kt:22)
        at kotlinx.coroutines.Dispatchers.getMain(Dispatchers.kt:58)
        at com.arkivanov.mvikotlin.extensions.coroutines.SuspendExecutor.<init>(SuspendExecutor.kt:23)
        at com.shabinder.common.main.store.SpotiFlyerMainStoreProvider$ExecutorImpl.<init>(SpotiFlyerMainStoreProvider.kt:57)
        at com.shabinder.common.main.store.SpotiFlyerMainStoreProvider$provide$1$1.invoke(SpotiFlyerMainStoreProvider.kt)
        at com.shabinder.common.main.store.SpotiFlyerMainStoreProvider$provide$1$1.invoke(SpotiFlyerMainStoreProvider.kt)
        at **com.arkivanov.mvikotlin.main.store.DefaultStore.<init>(DefaultStore.kt:31)**
        ... 143 more

![image](https://user-images.githubusercontent.com/44765050/107517071-48e26480-6bd3-11eb-9343-cebcd47a13db.png)

My Store Creator: 
![image](https://user-images.githubusercontent.com/44765050/107517165-63b4d900-6bd3-11eb-9a46-87f688c6801e.png)

My Suspend Executor: 
![image](https://user-images.githubusercontent.com/44765050/107517275-9232b400-6bd3-11eb-8890-20c7c1341761.png)

All methods like openPlatform,etc are just expect/actual empty blocks
![image](https://user-images.githubusercontent.com/44765050/107517458-c9a16080-6bd3-11eb-81cd-685e934f15d9.png)

**Comment by Shabinder** [comment]
All Implementations Are very similar to as shown in todo app , except these are coroutine/suspend instead of Reaktive

**Comment by Shabinder** [comment]
Crash is in Desktop only , same implementation works good in Android app(All Code is Common/Shared module)

**Comment by arkivanov** [comment]
Hello, this issue is not related to Decompose. Could you please raise it for MVIKotlin? Thanks!

**Comment by Shabinder** [comment]
oops , posted at wrong place, will raise issue in MVIKotlin.
